#!/bin/bash
echo "Cisco NAT Configuration"
echo
read -p 'WAN Interface: ' wanif
read -p 'WAN IP: ' wanip
read -p 'WAN MASK: ' wansn
read -p 'LAN Interface: ' lanif
read -p 'LAN IP: ' lanip
read -p 'LAN MASK: ' lansn
echo
echo "
SOF

conf t
en
hostname NAT-R
int $wanif
 ip address $wanip $wansn
 no shut
 ip nat outside
int $lanif
 ip address $lanip $lansn
 no shut
 ip nat inside
exit
!
ip nat pool natpoolname $wanip $wanip netmask $wansn
access-list 1 permit $lanip 0.0.0.255
ip nat inside source list 1 pool natpoolname overload
end
wr
!

EOF
"
echo "!!! NAT pool name is case sensitive"
echo
read -p '[Press ENTER key to exit]'
